### ISSUE TITLE
Got error inflatin class com.santalu... after update to 1.1.0

### ISSUE THREAD

**Issue by zhed** [santalu/mask-edittext#15]
Hi Mr. Fatih..
Thanks for this nice library,,
i've used it since 1.0.9,
got error after migrating to androidx & updated this lib to version 1.1.0,
Should i updated it or better stay in v1.0.9?

**Comment by santalu** [comment]
Hi zhed. 

Thank you for using this library. I've changed package name for the library because it was causing issues with my other libraries when using multiple of them in same project. It's now **com.santalu.maskedittext.MaskEditText**

Can you please check and paste full error stack trace in here. Thanks again.

**Comment by zhed** [comment]
Just read your reply and try the update, 
and it works great again on 1.1.1
Many thanks Fatih...
